apiVersion: apps/v1
kind: Deployment
metadata:
  name: velp-frontend
  namespace: velp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: velp-frontend
  template:
    metadata:
      labels:
        app: velp-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/zxx/velp-frontend:prod # 请根据实际修改
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: velp-frontend-service
  namespace: velp
spec:
  selector:
    app: velp-frontend
  ports:
  - port: 80
    targetPort: 80
